version: '2'
services:
    couchdb:
        build: ./couchdb
        ports:
            - "5984:5984"
        networks:
            - db-tier
        environment:
            COUCHDB_USER: 'admin'
            COUCHDB_PASSWORD: 'admin'
        volumes:
            - ./couchdb/data:/opt/couchdb/data
    backend:
        depends_on:
            - couchdb
        build: ..
        ports:
            - "3456:3456"
        environment:
            COUCHDB_HOST: 'couchdb'
            COUCHDB_PORT: '5984'
        networks:
            - db-tier
            - front-tier
        volumes:
            - ../dist:/usr/src/petshop/dist
    frontend:
        depends_on:
            - backend
        build: ../petshop
        ports:
            - "3000:3000"
        networks:
            - front-tier
        volumes:
            - ../petshop:/home/polymer/app

networks:
    front-tier:
        driver: bridge
    db-tier:
        driver: bridge
